// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pronect.RecordServer.DbContext;

namespace Pronect.RecordServer.DbContext.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20180424210903_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571");

            modelBuilder.Entity("Pronect.RecordServer.DbContext.Models.ConnectionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id");

                    b.Property<string>("EndTime")
                        .HasColumnName("end_time");

                    b.Property<string>("HostConnectionId")
                        .HasColumnName("host");

                    b.Property<string>("RemoteConnectionId")
                        .HasColumnName("remote");

                    b.Property<string>("StartTime")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.ToTable("connnection_records");
                });
#pragma warning restore 612, 618
        }
    }
}
