'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Song_Search.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to              Blessed Be the Name            Christian Hymnal 3          1. All praise to him who reigns above in majesty supreme who gave his son for man to die that he might man redeem. 2. His name above all names shall stand exalted more and more at God the Fathers own right hand where angels host adore. 3. Redeemer saviour friend of man once ruined by the fall thou hast devised salvations plan for thou hast died for all. 4. His name shall be the counselor the mighty prince of peace of all earths kingdoms [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property blessbe() As String
            Get
                Return ResourceManager.GetString("blessbe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to                 Bless Jehovah           Christian Hymnal 2               1. O my soul bless thou Jehova all within me bless his name bless jehovah and forget not all his mercies to proclaim. 2. Who forgives all my transgressions thy diseases all who heals who redeams thee from destruction who with thee so kindly deals. 3. Who with tender mercies crowns thee who with good things fill thy mouth so that even like an eagle thou hast been restored to youth. 4. In his righteousness jehovah will deliver those dist [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property blessedjeh() As String
            Get
                Return ResourceManager.GetString("blessedjeh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   Come Thou Almighty King         Christian Hymnal 1         1. Come thou almighty king help us thy name to sing help us to praise father all glorious oer all victorious come and reign over us ancient of days. 2. Come thou incarnate word gird on thy mighty sword our prayer attend come and thy people bless and give thy word success spirit of holiness on us descend. 3. Come holy comforter thy sacred witness bear in this glad hour thou who our mighty art now rule in every heart and neer from us depart spirit o [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property comethou() As String
            Get
                Return ResourceManager.GetString("comethou", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to               Glory to His Name           Christian Hymnal 4             1. Down at the cross where my saviour died down where for cleansing from sin i cried there to my heart was blood applied glory to his name i am so wondrously saved from sin jesus so sweetly abides within there at the cross where he took me in glory to his name oh precious fountain that saves from sin i am so glad i entered in there jesus saves me and keeps me clean glory to his name come to this fountain so rich and sweet cast thy poor [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property glorytohis() As String
            Get
                Return ResourceManager.GetString("glorytohis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property s() As String
            Get
                Return ResourceManager.GetString("s", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property s10() As String
            Get
                Return ResourceManager.GetString("s10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property s11() As String
            Get
                Return ResourceManager.GetString("s11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property s12() As String
            Get
                Return ResourceManager.GetString("s12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property s13() As String
            Get
                Return ResourceManager.GetString("s13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property s7() As String
            Get
                Return ResourceManager.GetString("s7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property s8() As String
            Get
                Return ResourceManager.GetString("s8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property s9() As String
            Get
                Return ResourceManager.GetString("s9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to                              Sing About Jesus    Christian Hymnal 5          1. Sing about Jesus who died to save who for my soul his life he gave sing for hes reigning above the grave. 2. Sing about Jesus He took me in sing of his power he saves from sin sing of his grace he keeps  me clean. 3. Sing about jesus our righteousness sing for he came my soul to bless while i with gladness his name confess. 4. sing about jesus both day and night this is my theme my hearts delight sing in the spirit for it is rig [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property singabout() As String
            Get
                Return ResourceManager.GetString("singabout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to           Worthy Art Thou, Lord Divine   Christian Hymnal 6       1. Worthy art thou lord divine to recieve this praise of mine to recieve this grateful praise of mine mercy hast thou shown to me and my soul delights in thee joyfully my soul delights in thee 2. From the dawn of my first day thou hast lead me all the way guided loved and kept me all the way and thy life blood thou didst give that forever I may live that with thee forever I may live 3. All my guilt thou didst remove  in thy great redeeming lo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property worthyart() As String
            Get
                Return ResourceManager.GetString("worthyart", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
