//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daquest_WPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data\t( { \"book\": [ {\"book_ref\":\"Ac\", \"book_name\":\"Acts\", \"book_nr\":\"44\", \"chapter" +
            "_nr\":\"3\", \"chapter\":{ \"4\":{ \"verse_nr\":\"4\", \"verse\":\"And Peter, fastening his ey" +
            "es upon him with John, said, Look on us.\"}, \"5\":{\"verse_nr\":5,\"verse\":\"And he ga" +
            "ve heed unto them, expecting to receive something of them.\"}, \"6\":{\"verse_nr\":6," +
            "\"verse\":\"Then Peter said, Silver and gold have I none; but such as I have give I" +
            " thee: In the name of Jesus Christ of Nazareth rise up and walk.\"},\"7\":{\"verse_n" +
            "r\":7,\"verse\":\"And he took him by the right hand, and lifted him up: and immediat" +
            "ely his feet and ankle bones received strength.\"},\"8\":{\"verse_nr\":8,\"verse\":\"And" +
            " he leaping up stood, and walked, and entered with them into the temple, walking" +
            ", and leaping, and praising God.\"},\"9\":{\"verse_nr\":9,\"verse\":\"And all the people" +
            " saw him walking and praising God:\"},\"10\":{\"verse_nr\":10,\"verse\":\"And they knew " +
            "that it was he which sat for alms at the Beautiful gate of the temple: and they " +
            "were filled with wonder and amazement at that which had happened unto him.\"},\"11" +
            "\":{\"verse_nr\":11,\"verse\":\"And as the lame man which was healed held Peter and Jo" +
            "hn, all the people ran together unto them in the porch that is called Solomon\'s," +
            " greatly wondering.\"},\"12\":{\"verse_nr\":12,\"verse\":\"And when Peter saw it, he ans" +
            "wered unto the people, Ye men of Israel, why marvel ye at this? or why look ye s" +
            "o earnestly on us, as though by our own power or holiness we had made this man t" +
            "o walk?\"},\"13\":{\"verse_nr\":13,\"verse\":\"The God of Abraham, and of Isaac, and of " +
            "Jacob, the God of our fathers, hath glorified his Son Jesus; whom ye delivered u" +
            "p, and denied him in the presence of Pilate, when he was determined to let him g" +
            "o.\"},\"14\":{\"verse_nr\":14,\"verse\":\"But ye denied the Holy One and the Just, and d" +
            "esired a murderer to be granted unto you;\"},\"15\":{\"verse_nr\":15,\"verse\":\"And kil" +
            "led the Prince of life, whom God hath raised from the dead; whereof we are witne" +
            "sses.\"},\"16\":{\"verse_nr\":16,\"verse\":\"And his name through faith in his name hath" +
            " made this man strong, whom ye see and know: yea, the faith which is by him hath" +
            " given him this perfect soundness in the presence of you all.\"},\"17\":{\"verse_nr\"" +
            ":17,\"verse\":\"And now, brethren, I wot that through ignorance ye did it, as did a" +
            "lso your rulers.\"} } } ,{ \"book_ref\":\"Ac\", \"book_name\":\"Acts\", \"book_nr\":\"44\", \"" +
            "chapter_nr\":\"2\", \"chapter\": {\"1\": {\"verse_nr\":\"1\", \"verse\":\"And when the day of " +
            "Pentecost was fully come, they were all with one accord in one place.\"}}}],\"dire" +
            "ction\":\"LTR\",\"type\":\"verse\",\"version\":\"kjv\"});\t\r\n")]
        public string data {
            get {
                return ((string)(this["data"]));
            }
            set {
                this["data"] = value;
            }
        }
    }
}
