// <auto-generated />
using System;
using ChurchDirectory.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ChurchDirectory.DbContext.Migrations
{
    [DbContext(typeof(DirectoryDbContext))]
    [Migration("20180720143114_RemoveChildList")]
    partial class RemoveChildList
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571");

            modelBuilder.Entity("ChurchDirectory.DbContext.Models.Child", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnName("birthdate");

                    b.Property<string>("Comment1")
                        .HasColumnName("comment1");

                    b.Property<string>("DeathDate")
                        .HasColumnName("deathdate");

                    b.Property<string>("Married")
                        .HasColumnName("married");

                    b.Property<bool>("Member")
                        .HasColumnName("member");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<string>("ParentId")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.ToTable("children");
                });

            modelBuilder.Entity("ChurchDirectory.DbContext.Models.Family", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnName("birthdate");

                    b.Property<string>("City")
                        .HasColumnName("city");

                    b.Property<string>("Comment1")
                        .HasColumnName("comment1");

                    b.Property<string>("Comment2")
                        .HasColumnName("comment2");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnName("deathdate");

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnName("last_name");

                    b.Property<string>("Line1")
                        .HasColumnName("line1");

                    b.Property<DateTime?>("MarriedDate")
                        .HasColumnName("marrieddate");

                    b.Property<string>("Member")
                        .HasColumnName("member");

                    b.Property<string>("ParentId")
                        .HasColumnName("parent_id");

                    b.Property<string>("Phone1")
                        .HasColumnName("phone1");

                    b.Property<string>("Phone2")
                        .HasColumnName("phone2");

                    b.Property<string>("RecordNumber")
                        .HasColumnName("record_number");

                    b.Property<string>("Spouse")
                        .HasColumnName("spouse");

                    b.Property<DateTime?>("SpouseBirthDate")
                        .HasColumnName("spouse_birthdate");

                    b.Property<DateTime?>("SpouseDeathDate")
                        .HasColumnName("spouse_deathdate");

                    b.Property<string>("SpouseId")
                        .HasColumnName("spouse_id");

                    b.Property<string>("State")
                        .HasColumnName("state");

                    b.Property<string>("Zip")
                        .HasColumnName("zip");

                    b.HasKey("Id");

                    b.ToTable("families");
                });
#pragma warning restore 612, 618
        }
    }
}
