// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pronect.DeviceServer.DbContext;

namespace Pronect.DeviceServer.DbContext.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20180428175936_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571");

            modelBuilder.Entity("Pronect.DirectoryServer.DbContext.Models.PronectDevice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Account")
                        .HasColumnName("account");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<string>("PermanentPassword")
                        .HasColumnName("temp_password");

                    b.Property<bool>("SignedIn")
                        .HasColumnName("signed_in");

                    b.Property<string>("TempPassword");

                    b.HasKey("Id");

                    b.ToTable("devices");
                });
#pragma warning restore 612, 618
        }
    }
}
