// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pronect.UserAccountServer.DbContext;

namespace Pronect.UserAccountServer.DbContext.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20180424201844_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571");

            modelBuilder.Entity("Pronect.UserAccountServer.DbContext.Models.UserAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id");

                    b.Property<string>("DateAcquired")
                        .HasColumnName("date_acquired");

                    b.Property<string>("Devices")
                        .HasColumnName("devices");

                    b.Property<string>("LicenseKey")
                        .HasColumnName("license_key");

                    b.Property<string>("OwnersName")
                        .HasColumnName("owners_name");

                    b.Property<string>("Password")
                        .HasColumnName("password");

                    b.Property<string>("WatchedDevices")
                        .HasColumnName("watched_devices");

                    b.HasKey("Id");

                    b.ToTable("user_accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
